### ISSUE TITLE
activerecord-jdbcmysql-adapter causing error for truncation

### ISSUE THREAD

**Issue by pareeohnos** [DatabaseCleaner/database_cleaner-active_record#25]
We have an application that needs to support multiple database engines, so our `Gemfile` contains multiple JDBC adapters as so:

```
gem 'activerecord-jdbcpostgresql-adapter', '~>1.3.7'
gem 'activerecord-jdbcmssql-adapter', '~>1.3.7'
gem 'activerecord-jdbcmysql-adapter', '~>1.3.7'
```

The app works as we expect, and each setup with a different database works well, however we've just introduced the `mysql` adapter, and have now found that the database cleaner is failing to `truncate` the database.

On my machine, I have a `postgres` database running. If I open up a rails console, and attempt to clean the database with `:truncation` I get the following error

```
TypeError: superclass mismatch for class Mysql2Adapter
```

We haven't changed any code in our app, and if I comment out the mysql JDBC adapter from the `Gemfile` and bundle install again, I am once again able to clean the database.

This is the stack trace that I get with the error

```
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/active_record/truncation.rb:209:in `ConnectionAdapters'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/active_record/truncation.rb:176:in `ActiveRecord'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/active_record/truncation.rb:175:in `(root)'
from org/jruby/RubyKernel.java:1065:in `require'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/base.rb:1:in `(root)'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/base.rb:108:in `orm_strategy'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/base.rb:34:in `create_strategy'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/base.rb:38:in `clean_with'
from org/jruby/RubyArray.java:1613:in `each'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/configuration.rb:85:in `clean_with'
from /Users/adrianh/.rvm/gems/jruby-1.7.12/gems/database_cleaner-1.0.1/lib/database_cleaner/configuration.rb:85:in `clean_with'
```

It's very similar (exact same error message) to other issues I've found here, however the line numbers are different so I'm assuming the issue is something different, given that the others have also been resolved and this is still appearing.

**Comment by etagwerker** [comment]
@pareeohnos Unfortunately at the moment `database_cleaner-active_record` doesn't support JDBC adapters. I'd love it if someone took the time to add support.

**Comment by pareeohnos** [comment]
@etagwerker I'd have loved to have helped, but I no longer work on this project nor use jruby so wouldn't be of much help I'm afraid
