### ISSUE TITLE
require 'database_cleaner/active_record' fails with rails 4.2.11.1

### ISSUE THREAD

**Issue by kramuenke** [DatabaseCleaner/database_cleaner-active_record#36]
Hi,

we upgraded from 1.7.0 to 1.8.2 and now getting the following error when running specs

```
An error occurred while loading spec_helper.
Failure/Error: require 'database_cleaner/active_record'

ArgumentError:
  Delegation needs a target. Supply an options hash with a :to key as the last argument (e.g. delegate :hello, to: :greeter).
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/core_ext/module/delegation.rb:154:in `delegate'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/base.rb:56:in `<class:Base>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/base.rb:8:in `<module:DatabaseCleaner>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/base.rb:7:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/configuration.rb:1:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner.rb:3:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-active_record-1.8.0/lib/database_cleaner/active_record.rb:2:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# ./spec/spec_helper.rb:24:in `<top (required)>'

```

**Comment by botandrose** [comment]
Closing to lack of activity, and since AR v4 has been EOL for years now.
