### ISSUE TITLE
Issue with the upcoming Factory Bot Rails due to lacking of lazy load hooks

### ISSUE THREAD

**Issue by tagliala** [DatabaseCleaner/database_cleaner-active_record#89]
Hello,

I'm using `database_cleaner-active_record` together with `factory-bot-rails` in an application.

The issue is documented here: thoughtbot/factory_bot_rails#426

Here it is a reproducible test case:

```rb
# frozen_string_literal: true

require 'bundler/inline'

begin
  gemfile(true) do
    source 'https://rubygems.org'

    gem 'pg'
    gem 'rails'
    # Comment out `git` and `branch` params to use the latest stable version of factory bot and make the test pass
    gem 'factory_bot_rails', git: 'https://github.com/thoughtbot/factory_bot_rails.git', branch: 'main'
    gem 'database_cleaner-active_record'
  end

  require 'active_record'
  require 'factory_bot_rails'
  require 'database_cleaner-active_record'
rescue Gem::LoadError => e
  puts "\nMissing Dependency:\n#{e.backtrace.first} #{e.message}"
rescue LoadError => e
  puts "\nError:\n#{e.backtrace.first} #{e.message}"
  exit 1
end

puts 'Ok'
```

Error:

```
~/.rvm/gems/ruby-3.2.2/gems/railties-7.1.1/lib/rails.rb:51:in `configuration': undefined method `config' for nil:NilClass (NoMethodError)

      application.config
                 ^^^^^^^
	from ~/.rvm/gems/ruby-3.2.2/bundler/gems/factory_bot_rails-fd1ca67b43f4/lib/factory_bot_rails/railtie.rb:25:in `block in <class:Railtie>'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:77:in `each'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
	from ~/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.1/lib/active_record/base.rb:338:in `<module:ActiveRecord>'
	from ~/.rvm/gems/ruby-3.2.2/gems/activerecord-7.1.1/lib/active_record/base.rb:15:in `<top (required)>'
	from <internal:~/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:~/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from ~/.rvm/gems/ruby-3.2.2/gems/database_cleaner-active_record-2.1.0/lib/database_cleaner/active_record/truncation.rb:2:in `<top (required)>'
	from <internal:~/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:~/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from ~/.rvm/gems/ruby-3.2.2/gems/database_cleaner-active_record-2.1.0/lib/database_cleaner/active_record.rb:4:in `<top (required)>'
	from <internal:~/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:~/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from ~/.rvm/gems/ruby-3.2.2/gems/database_cleaner-active_record-2.1.0/lib/database_cleaner-active_record.rb:1:in `<top (required)>'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `require'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `each'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `block in require'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `each'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `require'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/inline.rb:66:in `block (2 levels) in gemfile'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/settings.rb:140:in `temporary'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/inline.rb:51:in `block in gemfile'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler.rb:411:in `block in with_unbundled_env'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler.rb:657:in `with_env'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler.rb:411:in `with_unbundled_env'
	from ~/.rvm/gems/ruby-3.2.2/gems/bundler-2.4.20/lib/bundler/inline.rb:42:in `gemfile'
```

It is due to the fact that Database Cleaner does not use lazy hooks before using ActiveRecord. You can see a fix to the same issue with another gem here: amoeba-rb/amoeba#115

However, the fix does not appear to be so trivial with Database Cleaner, so this is why I'm opening an issue rather than submitting a PR

**Comment by tagliala** [comment]
Hopefully this will be addressed by Factory Bot Rails itself in thoughtbot/factory_bot_rails#432

**Comment by jamesw** [comment]
Having the same issue here

**Comment by tagliala** [comment]
Please try with the branch used in https://github.com/thoughtbot/factory_bot_rails/pull/432

**Comment by benoittgt** [comment]
I think this gem should follow lazy loading like other project:
- https://github.com/paper-trail-gem/paper_trail/commit/fc6c5f69410f1b79e617610d522dbedfa4f04f7f
- https://github.com/rails/rails/issues/46567
